name: Build
'on':
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.4.x'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install mm-snap
        run: npm install -g @metamask/snaps-cli
      - name: Install Dependencies and build snap
        run: |
          cd src
          yarn install
          mm-snap build
